export const PERMISSIONS = {
  APPLICATIONS_READ: 'applications.read',
  APPLICATIONS_REVIEW: 'applications.review',
  APPLICATIONS_ADMIT: 'applications.admit',
  STUDENTS_READ: 'students.read',
  STUDENTS_MANAGE: 'students.manage',
  ACADEMICS_READ: 'academics.read',
  ACADEMICS_MANAGE: 'academics.manage',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ASSESSMENTS_READ: 'assessments.read',
  ASSESSMENTS_MANAGE: 'assessments.manage',
  GRADING_READ: 'grading.read',
  GRADING_MANAGE: 'grading.manage',
  REPORTS_READ: 'reports.read',
  REPORTS_PUBLISH: 'reports.publish',
  FINANCE_READ: 'finance.read',
  FINANCE_MANAGE: 'finance.manage',
  PAYMENTS_MANAGE: 'payments.manage',
  PAYROLL_READ: 'payroll.read',
  PAYROLL_MANAGE: 'payroll.manage',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_MANAGE: 'inventory.manage',
  ANNOUNCEMENTS_MANAGE: 'announcements.manage',
  AUDIT_READ: 'audit.read',
  STAFF_READ: 'staff.read',
  STAFF_MANAGE: 'staff.manage',
  WALLET_READ: 'wallet.read',
  WALLET_TOP_UP: 'wallet.top_up',
  WALLET_MANAGE: 'wallet.manage',
  USERS_MANAGE: 'users.manage',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];